# Generated by Django 6.0.3 on 2026-04-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subject_studentenrollment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='accounts_st_student_548e35_idx',
            old_name='accounts_st_student_idx',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='accounts_su_year_le_ec7ed4_idx',
            old_name='accounts_su_year_le_idx',
        ),
    ]
