# Generated by Django 6.0.3 on 2026-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
