# Generated by Django 6.0.3 on 2026-04-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], max_length=1),
        ),
    ]
