# Generated by Django 6.0.3 on 2026-04-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_subject_is_active_subject_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'semester', 'school_year')},
        ),
        migrations.AlterField(
            model_name='subject',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('schedule_day', models.CharField(max_length=20)),
                ('schedule_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='faces.subject')),
            ],
            options={
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
